
version: "3"
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-CU6-ubuntu-16.04
    container_name: mssql-test
    ports:
      - "11433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=h0geh0ge 
      - MSSQL_PID=Express
      - MSSQL_LCID=1041
      - MSSQL_COLLATION=Japanese_CI_AS
