version: "3"
services:
    db:
        build: ./
        environment:
            SA_PASSWORD: "B!ng_2023"
            ACCEPT_EULA: "Y"
            MSSQL_AGENT_ENABLED: "true"
        ports:
            - "1433:1433"
        container_name: sql1
        hostname: sql1
        volumes:
            - SQLdatabase:/var/opt/mssql
            - ./backup:/backup
volumes:
    SQLdatabase:
        driver: local
